services:
  - type: web
    name: detecting-plant-diseases-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port 8000
    pythonVersion: 3.11.9
